/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOverviewImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedFoodConversionImport } from './routes/_authenticated/food-conversion'
import { Route as AuthenticatedFoodImport } from './routes/_authenticated/food'
import { Route as AuthenticatedExercisesImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedDietImport } from './routes/_authenticated/diet'
import { Route as AuthenticatedChangePasswordImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated/users/index'
import { Route as AuthLoginIndexImport } from './routes/_auth/login/index'
import { Route as AuthenticatedUsersUserIndexImport } from './routes/_authenticated/users/$user/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedOverviewRoute = AuthenticatedOverviewImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedFoodConversionRoute =
  AuthenticatedFoodConversionImport.update({
    id: '/food-conversion',
    path: '/food-conversion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedFoodRoute = AuthenticatedFoodImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedExercisesRoute = AuthenticatedExercisesImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDietRoute = AuthenticatedDietImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthenticatedUsersUserIndexRoute =
  AuthenticatedUsersUserIndexImport.update({
    id: '/users/$user/',
    path: '/users/$user/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/diet': {
      id: '/_authenticated/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof AuthenticatedDietImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/food': {
      id: '/_authenticated/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof AuthenticatedFoodImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/food-conversion': {
      id: '/_authenticated/food-conversion'
      path: '/food-conversion'
      fullPath: '/food-conversion'
      preLoaderRoute: typeof AuthenticatedFoodConversionImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/users/$user/': {
      id: '/_authenticated/users/$user/'
      path: '/users/$user'
      fullPath: '/users/$user'
      preLoaderRoute: typeof AuthenticatedUsersUserIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDietRoute: typeof AuthenticatedDietRoute
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRoute
  AuthenticatedFoodRoute: typeof AuthenticatedFoodRoute
  AuthenticatedFoodConversionRoute: typeof AuthenticatedFoodConversionRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedUsersUserIndexRoute: typeof AuthenticatedUsersUserIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDietRoute: AuthenticatedDietRoute,
  AuthenticatedExercisesRoute: AuthenticatedExercisesRoute,
  AuthenticatedFoodRoute: AuthenticatedFoodRoute,
  AuthenticatedFoodConversionRoute: AuthenticatedFoodConversionRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedUsersUserIndexRoute: AuthenticatedUsersUserIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/diet': typeof AuthenticatedDietRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/food': typeof AuthenticatedFoodRoute
  '/food-conversion': typeof AuthenticatedFoodConversionRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login': typeof AuthLoginIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/users/$user': typeof AuthenticatedUsersUserIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/diet': typeof AuthenticatedDietRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/food': typeof AuthenticatedFoodRoute
  '/food-conversion': typeof AuthenticatedFoodConversionRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login': typeof AuthLoginIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/users/$user': typeof AuthenticatedUsersUserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/diet': typeof AuthenticatedDietRoute
  '/_authenticated/exercises': typeof AuthenticatedExercisesRoute
  '/_authenticated/food': typeof AuthenticatedFoodRoute
  '/_authenticated/food-conversion': typeof AuthenticatedFoodConversionRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/users/$user/': typeof AuthenticatedUsersUserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/change-password'
    | '/diet'
    | '/exercises'
    | '/food'
    | '/food-conversion'
    | '/overview'
    | '/profile'
    | '/login'
    | '/users'
    | '/users/$user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/change-password'
    | '/diet'
    | '/exercises'
    | '/food'
    | '/food-conversion'
    | '/overview'
    | '/profile'
    | '/login'
    | '/users'
    | '/users/$user'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/change-password'
    | '/_authenticated/diet'
    | '/_authenticated/exercises'
    | '/_authenticated/food'
    | '/_authenticated/food-conversion'
    | '/_authenticated/overview'
    | '/_authenticated/profile'
    | '/_auth/login/'
    | '/_authenticated/users/'
    | '/_authenticated/users/$user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_authenticated"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/change-password",
        "/_authenticated/diet",
        "/_authenticated/exercises",
        "/_authenticated/food",
        "/_authenticated/food-conversion",
        "/_authenticated/overview",
        "/_authenticated/profile",
        "/_authenticated/users/",
        "/_authenticated/users/$user/"
      ]
    },
    "/_authenticated/change-password": {
      "filePath": "_authenticated/change-password.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/diet": {
      "filePath": "_authenticated/diet.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/exercises": {
      "filePath": "_authenticated/exercises.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/food": {
      "filePath": "_authenticated/food.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/food-conversion": {
      "filePath": "_authenticated/food-conversion.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/overview": {
      "filePath": "_authenticated/overview.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_auth/login/": {
      "filePath": "_auth/login/index.tsx",
      "parent": "/_auth"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/$user/": {
      "filePath": "_authenticated/users/$user/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
