/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLoginIndexImport } from './routes/_auth/login/index'
import { Route as AuthenticateduserProfileImport } from './routes/_authenticated/(user)/profile'
import { Route as AuthenticateduserOverviewImport } from './routes/_authenticated/(user)/overview'
import { Route as AuthenticateduserFoodConversionImport } from './routes/_authenticated/(user)/food-conversion'
import { Route as AuthenticateduserDietImport } from './routes/_authenticated/(user)/diet'
import { Route as AuthenticateduserChangePasswordImport } from './routes/_authenticated/(user)/change-password'
import { Route as AuthenticatedsystemFoodImport } from './routes/_authenticated/(system)/food'
import { Route as AuthenticatedsystemExercisesImport } from './routes/_authenticated/(system)/exercises'
import { Route as AuthenticatedsystemUsersIndexImport } from './routes/_authenticated/(system)/users/index'
import { Route as AuthenticatedsystemUsersUserIndexImport } from './routes/_authenticated/(system)/users/$user/index'
import { Route as AuthenticatedsystemUsersUserWorkoutImport } from './routes/_authenticated/(system)/users/$user/workout'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthenticateduserProfileRoute = AuthenticateduserProfileImport.update({
  id: '/(user)/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticateduserOverviewRoute = AuthenticateduserOverviewImport.update({
  id: '/(user)/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticateduserFoodConversionRoute =
  AuthenticateduserFoodConversionImport.update({
    id: '/(user)/food-conversion',
    path: '/food-conversion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticateduserDietRoute = AuthenticateduserDietImport.update({
  id: '/(user)/diet',
  path: '/diet',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticateduserChangePasswordRoute =
  AuthenticateduserChangePasswordImport.update({
    id: '/(user)/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedsystemFoodRoute = AuthenticatedsystemFoodImport.update({
  id: '/(system)/food',
  path: '/food',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedsystemExercisesRoute =
  AuthenticatedsystemExercisesImport.update({
    id: '/(system)/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedsystemUsersIndexRoute =
  AuthenticatedsystemUsersIndexImport.update({
    id: '/(system)/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedsystemUsersUserIndexRoute =
  AuthenticatedsystemUsersUserIndexImport.update({
    id: '/(system)/users/$user/',
    path: '/users/$user/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedsystemUsersUserWorkoutRoute =
  AuthenticatedsystemUsersUserWorkoutImport.update({
    id: '/(system)/users/$user/workout',
    path: '/users/$user/workout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/(system)/exercises': {
      id: '/_authenticated/(system)/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedsystemExercisesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(system)/food': {
      id: '/_authenticated/(system)/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof AuthenticatedsystemFoodImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(user)/change-password': {
      id: '/_authenticated/(user)/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticateduserChangePasswordImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(user)/diet': {
      id: '/_authenticated/(user)/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof AuthenticateduserDietImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(user)/food-conversion': {
      id: '/_authenticated/(user)/food-conversion'
      path: '/food-conversion'
      fullPath: '/food-conversion'
      preLoaderRoute: typeof AuthenticateduserFoodConversionImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(user)/overview': {
      id: '/_authenticated/(user)/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticateduserOverviewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(user)/profile': {
      id: '/_authenticated/(user)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticateduserProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthImport
    }
    '/_authenticated/(system)/users/': {
      id: '/_authenticated/(system)/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedsystemUsersIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(system)/users/$user/workout': {
      id: '/_authenticated/(system)/users/$user/workout'
      path: '/users/$user/workout'
      fullPath: '/users/$user/workout'
      preLoaderRoute: typeof AuthenticatedsystemUsersUserWorkoutImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/(system)/users/$user/': {
      id: '/_authenticated/(system)/users/$user/'
      path: '/users/$user'
      fullPath: '/users/$user'
      preLoaderRoute: typeof AuthenticatedsystemUsersUserIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedsystemExercisesRoute: typeof AuthenticatedsystemExercisesRoute
  AuthenticatedsystemFoodRoute: typeof AuthenticatedsystemFoodRoute
  AuthenticateduserChangePasswordRoute: typeof AuthenticateduserChangePasswordRoute
  AuthenticateduserDietRoute: typeof AuthenticateduserDietRoute
  AuthenticateduserFoodConversionRoute: typeof AuthenticateduserFoodConversionRoute
  AuthenticateduserOverviewRoute: typeof AuthenticateduserOverviewRoute
  AuthenticateduserProfileRoute: typeof AuthenticateduserProfileRoute
  AuthenticatedsystemUsersIndexRoute: typeof AuthenticatedsystemUsersIndexRoute
  AuthenticatedsystemUsersUserWorkoutRoute: typeof AuthenticatedsystemUsersUserWorkoutRoute
  AuthenticatedsystemUsersUserIndexRoute: typeof AuthenticatedsystemUsersUserIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedsystemExercisesRoute: AuthenticatedsystemExercisesRoute,
  AuthenticatedsystemFoodRoute: AuthenticatedsystemFoodRoute,
  AuthenticateduserChangePasswordRoute: AuthenticateduserChangePasswordRoute,
  AuthenticateduserDietRoute: AuthenticateduserDietRoute,
  AuthenticateduserFoodConversionRoute: AuthenticateduserFoodConversionRoute,
  AuthenticateduserOverviewRoute: AuthenticateduserOverviewRoute,
  AuthenticateduserProfileRoute: AuthenticateduserProfileRoute,
  AuthenticatedsystemUsersIndexRoute: AuthenticatedsystemUsersIndexRoute,
  AuthenticatedsystemUsersUserWorkoutRoute:
    AuthenticatedsystemUsersUserWorkoutRoute,
  AuthenticatedsystemUsersUserIndexRoute:
    AuthenticatedsystemUsersUserIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/exercises': typeof AuthenticatedsystemExercisesRoute
  '/food': typeof AuthenticatedsystemFoodRoute
  '/change-password': typeof AuthenticateduserChangePasswordRoute
  '/diet': typeof AuthenticateduserDietRoute
  '/food-conversion': typeof AuthenticateduserFoodConversionRoute
  '/overview': typeof AuthenticateduserOverviewRoute
  '/profile': typeof AuthenticateduserProfileRoute
  '/login': typeof AuthLoginIndexRoute
  '/users': typeof AuthenticatedsystemUsersIndexRoute
  '/users/$user/workout': typeof AuthenticatedsystemUsersUserWorkoutRoute
  '/users/$user': typeof AuthenticatedsystemUsersUserIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/exercises': typeof AuthenticatedsystemExercisesRoute
  '/food': typeof AuthenticatedsystemFoodRoute
  '/change-password': typeof AuthenticateduserChangePasswordRoute
  '/diet': typeof AuthenticateduserDietRoute
  '/food-conversion': typeof AuthenticateduserFoodConversionRoute
  '/overview': typeof AuthenticateduserOverviewRoute
  '/profile': typeof AuthenticateduserProfileRoute
  '/login': typeof AuthLoginIndexRoute
  '/users': typeof AuthenticatedsystemUsersIndexRoute
  '/users/$user/workout': typeof AuthenticatedsystemUsersUserWorkoutRoute
  '/users/$user': typeof AuthenticatedsystemUsersUserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/(system)/exercises': typeof AuthenticatedsystemExercisesRoute
  '/_authenticated/(system)/food': typeof AuthenticatedsystemFoodRoute
  '/_authenticated/(user)/change-password': typeof AuthenticateduserChangePasswordRoute
  '/_authenticated/(user)/diet': typeof AuthenticateduserDietRoute
  '/_authenticated/(user)/food-conversion': typeof AuthenticateduserFoodConversionRoute
  '/_authenticated/(user)/overview': typeof AuthenticateduserOverviewRoute
  '/_authenticated/(user)/profile': typeof AuthenticateduserProfileRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_authenticated/(system)/users/': typeof AuthenticatedsystemUsersIndexRoute
  '/_authenticated/(system)/users/$user/workout': typeof AuthenticatedsystemUsersUserWorkoutRoute
  '/_authenticated/(system)/users/$user/': typeof AuthenticatedsystemUsersUserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/exercises'
    | '/food'
    | '/change-password'
    | '/diet'
    | '/food-conversion'
    | '/overview'
    | '/profile'
    | '/login'
    | '/users'
    | '/users/$user/workout'
    | '/users/$user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/exercises'
    | '/food'
    | '/change-password'
    | '/diet'
    | '/food-conversion'
    | '/overview'
    | '/profile'
    | '/login'
    | '/users'
    | '/users/$user/workout'
    | '/users/$user'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/(system)/exercises'
    | '/_authenticated/(system)/food'
    | '/_authenticated/(user)/change-password'
    | '/_authenticated/(user)/diet'
    | '/_authenticated/(user)/food-conversion'
    | '/_authenticated/(user)/overview'
    | '/_authenticated/(user)/profile'
    | '/_auth/login/'
    | '/_authenticated/(system)/users/'
    | '/_authenticated/(system)/users/$user/workout'
    | '/_authenticated/(system)/users/$user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_authenticated"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/login/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/(system)/exercises",
        "/_authenticated/(system)/food",
        "/_authenticated/(user)/change-password",
        "/_authenticated/(user)/diet",
        "/_authenticated/(user)/food-conversion",
        "/_authenticated/(user)/overview",
        "/_authenticated/(user)/profile",
        "/_authenticated/(system)/users/",
        "/_authenticated/(system)/users/$user/workout",
        "/_authenticated/(system)/users/$user/"
      ]
    },
    "/_authenticated/(system)/exercises": {
      "filePath": "_authenticated/(system)/exercises.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(system)/food": {
      "filePath": "_authenticated/(system)/food.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(user)/change-password": {
      "filePath": "_authenticated/(user)/change-password.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(user)/diet": {
      "filePath": "_authenticated/(user)/diet.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(user)/food-conversion": {
      "filePath": "_authenticated/(user)/food-conversion.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(user)/overview": {
      "filePath": "_authenticated/(user)/overview.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(user)/profile": {
      "filePath": "_authenticated/(user)/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_auth/login/": {
      "filePath": "_auth/login/index.tsx",
      "parent": "/_auth"
    },
    "/_authenticated/(system)/users/": {
      "filePath": "_authenticated/(system)/users/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(system)/users/$user/workout": {
      "filePath": "_authenticated/(system)/users/$user/workout.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/(system)/users/$user/": {
      "filePath": "_authenticated/(system)/users/$user/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
